on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
        cache: true
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi
    - run: echo Test > build/app/outputs/apk/test.txt
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/apk/test.txt
        # path: build/app/outputs/apk/debug.apk
  deploy:
    name: Deploy App Distribution
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      id: download
      with:
        name: apk
        path: build/app/outputs/apk/test.txt
    - name: CAT
      run: cat ${{steps.download.outputs.download-path}}/test.txt
