on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - uses: actions/setup-java@v1
    #   with:
    #     distribution: 'zulu'
    #     java-version: '11'
    # - uses: subosito/flutter-action@v2
    #   with:
    #     flutter-version: '3.0.3'
    #     cache: true
    # - run: flutter pub get
    # - run: flutter build apk --debug --split-per-abi
    - run 
    - run: echo Test > android/test.txt
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: android/test.txt
        # path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk

  deploy:
    name: Deploy App Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: apk
        path: android/test.txt
    - name: CAT
      run: cat ${{steps.download.outputs.download-path}}/test.txt
