name: Build and Release apk
on:
  workflow_dispatch:
    inputs:
      release-note:
        required: true
        description: 'リリースノートを記入してください(%0Aで改行可能)'
      environment:
        type: environment
jobs:
  confirm:
    name: Confirm Input
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show Input
      run: |
          read version <<< `cat pubspec.yaml | grep ^version | sed -e "s/^version: //g"`
          echo Version: $version
          echo ReleaseNote: ${{github.event.inputs.release-note}}
  build:
    name: Build APK
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    steps:
    - uses: actions/checkout@v3
    - name: Create Tag
      run: | 
          read version <<< `cat pubspec.yaml | grep ^version | sed -e "s/^version: //g"`
          git tag $version
          git push origin $version
    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.3'
        cache: true
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi
    - uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk

  deploy:
    name: Deploy App Distribution
    needs: build
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      id: download
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-debug.apk
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: tester
        file: ${{steps.download.outputs.download-path}}/app-armeabi-v7a-debug.apk
        releaseNotes: ${{github.event.inputs.release-note}}
