on: 
  push:
    # paths:
    #   - 'pubspec.yaml'
name: Create Tag
jobs:
  create:
    name: Create Tag
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v3
    - name: Check Tags
      run: echo ${GITHUB_REF#refs/tags/}
