on: 
  push:
    paths:
      - 'pubspec.yaml'
name: Create Tag
jobs:
  create:
    name: Create Tag
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v3
    - name: Check Version Diff
      id: check
      run: | # 前回コミットと比較してversionが変わっているか
          git diff HEAD^ HEAD | grep ^+version:
          echo "::set-output name=result::$?"
    - name: Create Tag
      if: ${{steps.check.outputs.result == 0}}
      run: | 
          read version <<< `cat pubspec.yaml | grep ^version | sed -e "s/^version: //g"`
          git tag $version
          git push origin $version
